export const EMPTY_CASE = {
  title: '',
  specialty: 'Kardiologiya',
  difficulty: 'Orta',
  patient_summary: '',
  patient_context: '',
  tags: [],
  vitals: [
    { label: 'Təzyiq', value: '' },
    { label: 'Nabz', value: '' },
    { label: 'Temp', value: '' },
    { label: 'SpO2', value: '' },
  ],
  history_questions: [],
  examinations: [],
  investigations: [],
  differential_diagnosis: [],
  correct_diagnosis: '',
  diagnosis_keywords: [],
  explanation_points: [],
  treatment_options: [],
  treatment_points: [],
  is_published: false,
}
