export const allCases = [
  {
    id: 1,
    title: "Yorğunluq və arıqlama",
    specialty: "İnfeksion xəstəliklər",
    difficulty: "Çətin",
    patientSummary: "36 yaşlı kişi 6 aydır davam edən yorğunluq, aralıq temperatur, 7 kq çəki itkisi və xronik ishal şikayətləri ilə müraciət edir. Ağız boşluğunda yaralar və 3 həftədir güclənən quru öskürək qeyd edir. Dəfələrlə 'viral infeksiya' və 'IBS' diaqnozu ilə müalicə olunub, effekt yoxdur.",
    tags: ["36 yaş · Kişi", "Çəki itkisi", "Xronik ishal"],
    vitals: [
      { label: "Temp", value: "37.8°C" },
      { label: "Nəbz", value: "102" },
      { label: "AT", value: "108/70" },
      { label: "SpO2", value: "94%" },
    ],
    patientContext: `Sən 36 yaşlı Elnur adlı xəstəsən. 6 aydır yorğunluq, aralıq temperatur, 7 kq çəki itkisi və xronik ishal var. Ağız boşluğunda ağ örtük var, 3 həftədir quru öskürək var. Yük sürücüsüsən, tez-tez uzaq səfərlərə gedirsən. Birdən çox cinsi tərəfdaşın olub. İV narkotik istifadən olmayıb. Qan köçürməsi tarixçən yoxdur. Dəfələrlə "viral infeksiya" və "IBS" diaqnozu ilə müalicə olunmusan, effekt olmayıb. Cavablarını birinci şəxsdə, xəstə kimi ver — məsələn "Mənim..." deyə başla. Qısa və təbii danış, tibbi termin işlətmə.`,
    historyQuestions: [
      { q: "Peşəniz nədir?", a: "Yük sürücüsüyəm, tez-tez uzaq səfərlərə gedirəm." },
      { q: "Son bir ildə cinsi həyatınız necə olub?", a: "Birdən çox cinsi tərəfdaşım olub." },
      { q: "İV narkotik istifadəniz olubmu?", a: "Xeyr, heç vaxt istifadə etməmişəm." },
      { q: "Qan köçürməsi tarixçəniz varmı?", a: "Xeyr, belə bir tarixçəm yoxdur." },
    ],
    examinations: [
      { system: "Ağız boşluğu", finding: "Oral kandidiaz (ağ örtük) aşkar edildi — immunosuppressiyanın əlaməti" },
      { system: "Limfa düyünləri", finding: "Servikal və aksiller limfadenopatiya — ümumiləşmiş" },
      { system: "Ağciyərlər", finding: "Auskultasiyada ikitərəfli xırıltı eşidilir" },
      { system: "Dəri", finding: "Səpgi və sarılıq yoxdur" },
    ],
    investigations: [
      { test: "Tam qan analizi", result: "Normositar anemiya, CRP yüksək", relevant: true },
      { test: "Anti-HIV (ELISA)", result: "Müsbət — dərhal Western Blot ilə təsdiq lazımdır", relevant: true },
      { test: "CD4 sayı", result: "CD4: 180 hüceyrə/μL (normadan kəskin aşağı)", relevant: true },
      { test: "Döş qəfəsi rentgeni", result: "İkitərəfli interstisial infiltratlar — PCP ehtimalı", relevant: true },
      { test: "Qaraciyər fermentləri", result: "ALT/AST normada", relevant: false },
      { test: "Sidik analizi", result: "Normada", relevant: false },
    ],
    correctDiagnosis: "QİÇS (AIDS)",
    diagnosisKeywords: ["qiçs", "aids", "hiv", "immunodefisit"],
    explanationPoints: [
      "Anti-HIV müsbət, CD4 180 — AIDS mərhələsi",
      "Oral kandidiaz — immunosupressiyanın göstəricisi",
      "İkitərəfli ağciyər infiltratları — PCP pnevmoniyası",
      "Risk faktoru: çoxlu cinsi tərəfdaş",
      "Uzunmüddətli müalicəyə cavabsız simptomlar",
    ],
    treatmentPoints: [
      "Antiretroviral terapiya (ART): Tenofovir + Emtrisitabin + Efavirenz",
      "PCP profilaktikası: Kotrimoksazol",
      "Fırsatçı infeksiyaların müalicəsi",
      "CD4 və viral yük monitorinqi hər 3 ayda bir",
      "Psixoloji dəstək və yaxın kontaktların müayinəsi",
    ],
  },
  {
    id: 2,
    title: "Əldə yaralaşma",
    specialty: "İnfeksion xəstəliklər",
    difficulty: "Orta",
    patientSummary: "22 yaşlı çoban sol əlinin arxasında 7 həftədir yavaş-yavaş böyüyən yara ilə müraciət edir. Mal-qara yanında həşərat sancmasından sonra qaşınan papul kimi başlayıb, tədricən xoralanıb. Topikal antibiotiklər kömək etməyib.",
    tags: ["22 yaş · Kişi", "Dəri yarası", "Kənd bölgəsi"],
    vitals: [
      { label: "Temp", value: "36.9°C" },
      { label: "Nəbz", value: "76" },
      { label: "AT", value: "120/78" },
      { label: "SpO2", value: "99%" },
    ],
    patientContext: `Sən 22 yaşlı Tural adlı çobansa. Sol əlinin arxasında 7 həftədir böyüyən yara var. Həşərat sancmasından sonra başlayıb, getsə-getdikcə böyüyüb. Topikal antibiotiklər işə yaramayıb. Hər gün mal-qara ilə işləyirsən. Qonşu kənddə oxşar yarası olan birini tanıyırsan. Qızdırman yoxdur, ümumi vəziyyətin qənaətbəxşdir. Cavablarını birinci şəxsdə ver, sadə dillə danış.`,
    historyQuestions: [
      { q: "Peşəniz nədir, heyvanlarla təmasınız olurmu?", a: "Çobanam, hər gün mal-qara ilə işləyirəm." },
      { q: "Yara necə başladı?", a: "Həşərat sancmasından sonra qaşınan şişkinlik kimi başladı." },
      { q: "Antibiotik müalicəsi effektiv oldumu?", a: "Xeyr, topikal antibiotiklər heç bir dəyişiklik etmədi." },
      { q: "Bölgənizdə oxşar xəstəliklər olubmu?", a: "Qonşu kənddə oxşar yarası olan birini tanıyıram." },
    ],
    examinations: [
      { system: "Dəri yarası", finding: "2 sm xora, qaldırılmış indurasiyalı kənarlar, qranülyar baza — klassik 'vulkan kratı' görünüşü" },
      { system: "Limfa düyünləri", finding: "Kiçik, ağrısız epitroklear limfa düyünü palpasiya olunur" },
      { system: "Ümumi vəziyyət", finding: "Qızdırma yoxdur, ümumi vəziyyət qaneedicidir" },
    ],
    investigations: [
      { test: "Leishmania serologiyası (rK39)", result: "Müsbət — kutanöz leişmaniyoza dəlalət edir", relevant: true },
      { test: "Yara sürtüntüsü (Giemsa)", result: "Amastigotlar görünür — Leishmania spp. təsdiqləndi", relevant: true },
      { test: "Tam qan analizi", result: "Normada, ESR yüngül yüksək", relevant: true },
      { test: "Göbələk mədəniyyəti", result: "Mənfi", relevant: false },
      { test: "TST (tuberkulin)", result: "Mənfi", relevant: false },
    ],
    correctDiagnosis: "Kutanöz leişmaniyoz",
    diagnosisKeywords: ["leişmaniyoz", "leishmania", "kutanöz", "dəri leişmaniyoz"],
    explanationPoints: [
      "Çoban — heyvanlarla təmas, həşərat sancması riski yüksək",
      "Klassik indurasiyalı kənarlı xora görünüşü",
      "Antibiotiklərə cavabsızlıq — bakterial deyil",
      "rK39 serologiyası və Giemsa boyası müsbət",
      "Ağrısız limfadenopatiya — leişmaniyoz üçün xarakterik",
    ],
    treatmentPoints: [
      "Meglumin antimonat (Glucantime) — lokal inyeksiya",
      "Ağır hallarda: Amfoterisin B",
      "Yara baxımı və infeksiyanın qarşısının alınması",
      "Həşəratlara qarşı qoruyucu tədbirlər",
      "6 ay sonra nəzarət müayinəsi",
    ],
  },
  {
    id: 3,
    title: "Uzunsürən qızdırma",
    specialty: "İnfeksion xəstəliklər",
    difficulty: "Çətin",
    patientSummary: "25 yaşlı qadın 12 gündür davam edən qızdırma (39–40°C), qarın ağrısı və ishal şikayətləri ilə təcili yardıma müraciət edir. Son iki gündür artan zəiflik və şüur bulanıqlığı qeyd edir.",
    tags: ["25 yaş · Qadın", "12 günlük qızdırma", "Qarın ağrısı"],
    vitals: [
      { label: "Temp", value: "39.8°C" },
      { label: "Nəbz", value: "88" },
      { label: "AT", value: "100/65" },
      { label: "SpO2", value: "96%" },
    ],
    patientContext: `Sən 25 yaşlı Aytən adlı xəstəsən. 12 gündür yüksək qızdırman var (39-40°C), qarın ağrın var, ishal var. Son 2 gündür zəiflik və başın bulanır. 3 həftə əvvəl kənd ərazisinə getmişdin, orada müxtəlif su mənbəyindən içmişdin. Qızdırma yavaş-yavaş başlayıb, tədricən artıb. Son 2 gündür baş ağrın da var. Cavablarını birinci şəxsdə ver, özünü çox xəstə hiss edən biri kimi danış.`,
    historyQuestions: [
      { q: "Qızdırma nə vaxtdan başlayıb?", a: "12 gün əvvəl yavaş-yavaş başlayıb, tədricən artıb." },
      { q: "Kənd rayonuna səfəriniz olubmu?", a: "Bəli, 3 həftə əvvəl kənd ərazisinə getmişdim." },
      { q: "İçməli su mənbəyi necədir?", a: "Kənddə müxtəlif su mənbəyindən içmişdim." },
      { q: "Başqa simptomlar varmı?", a: "Bəli, son 2 gündür baş ağrım və yüngül başgicəllənmə var." },
    ],
    examinations: [
      { system: "Ümumi görünüş", finding: "Toksik görünüş, letarji" },
      { system: "Ürək-damar", finding: "Nisbi bradikardiya — qızdırmaya uyğun olmayan yavaş nəbz (xarakterik əlamət)" },
      { system: "Qarın", finding: "Sağ qasıq nahiyəsində ağrı, qarın şişkinliyi, bağırsaq səsləri azalmış" },
    ],
    investigations: [
      { test: "Qan mədəniyyəti", result: "Salmonella typhi üreməsi müsbət — tifozu təsdiqlər", relevant: true },
      { test: "Tam qan analizi", result: "Lökopenia: WBC 3.2×10⁹/L — xarakterik tapıntı", relevant: true },
      { test: "Widal testi", result: "Anti-O titrləri yüksək", relevant: true },
      { test: "Qarın rentgeni", result: "Hava-maye səviyyələri, pnevmoperitoneum şübhəsi — perforasiya riski!", relevant: true },
      { test: "ALT/AST", result: "Yüngül yüksəlmə", relevant: true },
      { test: "HBsAg", result: "Mənfi", relevant: false },
    ],
    correctDiagnosis: "Qarın tifi (Typhoid fever)",
    diagnosisKeywords: ["tif", "typhoid", "salmonella", "qarın tifi"],
    explanationPoints: [
      "Salmonella typhi qan mədəniyyətində üremişdir",
      "Nisbi bradikardiya — tif üçün klassik əlamət",
      "Lökopenia — bakterial infeksiya üçün qeyri-adi, tifə xasdır",
      "Kənd ərazisi, şübhəli su mənbəyi — risk faktoru",
      "Perforasiya riski — pnevmoperitoneum şübhəsi cərrahi konsultasiya tələb edir",
    ],
    treatmentPoints: [
      "Sefalosporinlər (Seftriakson 2q/gün IV) — birinci sıra",
      "Alternativ: Siprofloksasin (floroquinolon həssaslığı varsa)",
      "Yataq rejimi, hidrasiya",
      "Perforasiya şübhəsində cərrahi konsultasiya",
      "Epidemioloji araşdırma və kontaktların izlənməsi",
    ],
  },
  {
    id: 4,
    title: "Sarılıq və qaraciyər şişməsi",
    specialty: "İnfeksion xəstəliklər",
    difficulty: "Orta",
    patientSummary: "32 yaşlı kişi bir həftədir yorğunluq, ürək bulanması, tünd sidik və gözlərin sarıması ilə müraciət edir. Sarılıq başlamazdan əvvəl oynaq ağrısı və aşağı dərəcəli qızdırma olub. Üç ay əvvəl qorunmadan cinsi əlaqə tarixçəsi var.",
    tags: ["32 yaş · Kişi", "Sarılıq", "Qaraciyər"],
    vitals: [
      { label: "Temp", value: "37.4°C" },
      { label: "Nəbz", value: "82" },
      { label: "AT", value: "122/76" },
      { label: "SpO2", value: "98%" },
    ],
    patientContext: `Sən 32 yaşlı Kamran adlı xəstəsən. Bir həftədir yorğunluğun var, ürəyin bulanır, sidiin tündləşib, gözlərin sarılaşıb. Sarılıqdan 2 həftə əvvəl oynaq ağrın və hərarətin olmuşdu. 3 ay əvvəl qorunmadan cinsi əlaqən olub. Hepatit B əleyhinə peyvənd olmamısan. Assit və ensefalopatiya yoxdur. Cavablarını birinci şəxsdə ver, narahat amma sakit bir adam kimi danış.`,
    historyQuestions: [
      { q: "Sarılıq nə vaxtdan var?", a: "Təxminən 1 həftədir, gözlərim sarılaşıb, sidiyim tündləşib." },
      { q: "Əvvəlcə başqa simptomlar oldumu?", a: "Bəli, 2 həftə əvvəl oynaq ağrım və hərarətim olmuşdu." },
      { q: "Son vaxtlar cinsi əlaqəniz olubmu?", a: "3 ay əvvəl qorunmadan cinsi əlaqəm olub." },
      { q: "Peyvəndlənmisiniz?", a: "Xeyr, Hepatit B əleyhinə peyvənd olmamışam." },
    ],
    examinations: [
      { system: "Göz sklerası", finding: "İkterik skleralar — sarılıq aydın görünür" },
      { system: "Qarın", finding: "Qaraciyər yüngül böyümüş, kənarı düzgün, ağrılı" },
      { system: "Ümumi", finding: "Assit və ensefalopatiya yoxdur — qeyri-fulminant kurs" },
    ],
    investigations: [
      { test: "ALT/AST", result: "ALT: 1200 U/L, AST: 950 U/L — kəskin hepatoselülyar zədə", relevant: true },
      { test: "HBsAg", result: "Müsbət — aktiv HBV infeksiyası", relevant: true },
      { test: "Anti-HBc IgM", result: "Müsbət — kəskin infeksiya göstəricisi", relevant: true },
      { test: "Anti-HBs", result: "Mənfi — immunitet yoxdur", relevant: true },
      { test: "Ümumi bilirubin", result: "6.8 mg/dL (yüksək)", relevant: true },
      { test: "Anti-HCV", result: "Mənfi", relevant: false },
    ],
    correctDiagnosis: "Kəskin Hepatit B",
    diagnosisKeywords: ["hepatit b", "hbv", "kəskin hepatit", "hepatit"],
    explanationPoints: [
      "HBsAg müsbət + Anti-HBc IgM müsbət = kəskin HBV",
      "ALT 1200 U/L — kəskin hepatoselülyar zədə",
      "3 ay əvvəl qorunmadan cinsi əlaqə — inkubasiya dövrünə uyğun",
      "Peyvəndsizlik — risk faktoru",
      "Assit/ensefalopatiya yoxdur — fulminant deyil",
    ],
    treatmentPoints: [
      "Çox hallarda kəskin HBV özbaşına keçir — dəstəkləyici müalicə",
      "İstirahət, qaraciyərə zəhərli maddələrdən çəkinmə (alkohol, hepatotoksik dərmanlar)",
      "Fulminant hepatit varsa: Tenofovir",
      "Qaraciyər funksiyasına həftəlik nəzarət",
      "Yaxın kontaktların peyvəndi tövsiyə edilir",
    ],
  },
  {
    id: 5,
    title: "Göz düşməsi və udma çətinliyi",
    specialty: "İnfeksion xəstəliklər",
    difficulty: "Çətin",
    patientSummary: "37 yaşlı kişi 18 saat əvvəl başlayan görmə bulanıqlığı, göz qapağı sallanması (ptoz), udma çətinliyi və baş ağrısı ilə müraciət edir. Kənd ərazisindən gətirilən ev konservindən ət yemişdir.",
    tags: ["37 yaş · Kişi", "Neyroloji simptomlar", "Ev konservi"],
    vitals: [
      { label: "Temp", value: "36.6°C" },
      { label: "Nəbz", value: "68" },
      { label: "AT", value: "115/72" },
      { label: "SpO2", value: "96%" },
    ],
    patientContext: `Sən 37 yaşlı Rauf adlı xəstəsən. 18 saat əvvəl görmən bulanıb, göz qapaqların sallanıb, udmağa çətinlik çəkirsən, başın ağrıyır. 18 saat əvvəl ev konservindən ət yemişdin. Qardaşın da eyni yeməyi yeyib və ona da oxşar simptomlar başlayıb. Qızdırman yoxdur. Nəfəs almaq çətinləşib, özünü çox halsız hiss edirsən. Şüurun tam yerindədir. Cavablarını birinci şəxsdə ver, qorxmuş və zəif bir adam kimi danış.`,
    historyQuestions: [
      { q: "Nə yemişdiniz simptomlardan əvvəl?", a: "18 saat əvvəl ev konservindən ət yemişdim." },
      { q: "Başqa ailə üzvlərinin simptomları varmı?", a: "Bəli, eyni yeməyi yemiş qardaşımda da oxşar simptomlar başlayıb." },
      { q: "Qızdırma var mı?", a: "Xeyr, qızdırmam yoxdur." },
      { q: "Nəfəs almaqda çətinlik varmı?", a: "Bəli, nəfəsim çətinləşib, özümü çox halsız hiss edirəm." },
    ],
    examinations: [
      { system: "Göz", finding: "Sabit genişlənmiş göz bəbəkləri, oftalmoplegia — xarici göz əzələlərinin iflici" },
      { system: "Ağız/boğaz", finding: "Selikli qişalar quru, dysphonia (zəif səs), udma çətin" },
      { system: "Əzələ/reflektor", finding: "Ümumiləşmiş əzələ zəifliyi, hipotoniya, dərin vətər refleksləri azalmış" },
      { system: "Şüur", finding: "Şüur tam qorunub — botulizm üçün xarakterik" },
    ],
    investigations: [
      { test: "Botulinum toksini (qan/nəcis)", result: "Müsbət — Clostridium botulinum toksini təsdiqləndi", relevant: true },
      { test: "Elektromiaqrafiya (EMG)", result: "Neyromuskular blok — botulizm üçün xarakterik pattern", relevant: true },
      { test: "Spirometriya / tənəffüs funksiyası", result: "FVC azalıb — tənəffüs dəstəyi lazım ola bilər", relevant: true },
      { test: "KT beyin", result: "Normada — struktur patologiya yoxdur", relevant: false },
      { test: "Lumbal punksiya", result: "Normada — Guillain-Barré istisna olundu", relevant: false },
    ],
    correctDiagnosis: "Botulizm",
    diagnosisKeywords: ["botulizm", "botulinum", "clostridium botulinum"],
    explanationPoints: [
      "Ev konservi — Clostridium botulinum üçün əsas mənbə",
      "Ptoz, oftalmoplegia, udma çətinliyi — kranial sinir tutulması",
      "Qızdırma YOX — toksinin birbaşa təsiri, infeksiya deyil",
      "Şüur qorunub — botulizm üçün xarakterik",
      "Ailə üzvlərinin eyni yeməkdən xəstələnməsi — sübut",
    ],
    treatmentPoints: [
      "Botulinum antitoksini (trivalent) — mümkün qədər tez verin",
      "Tənəffüs dəstəyi — tənəffüs iflici riski var, ICU-ya qəbul",
      "Mədə yuma (yenilik yenicə qəbul edilmişsə)",
      "Dəstəkləyici qulluq — bəzən həftələr-aylar sürmür",
      "Epidemioloji bildiriş — qalan konserv məhsullarını imha et",
    ],
  },
  {
    id: 6,
    title: "Kəskin döş ağrısı",
    specialty: "Kardiologiya",
    difficulty: "Çətin",
    patientSummary: "58 yaşlı kişi 2 saatdan bəri davam edən kəskin, sıxıcı döş ağrısı, sol qola və çənəyə yayılma, güclü tərləmə və ürəkbulanması şikayəti ilə təcili yardıma müraciət edib. Hipertansiyon üzrə müalicə alır, uzun illərdir siqaret çəkir, son həftə dərmanını kəsmişdi.",
    tags: ["58 yaş · Kişi", "Kəskin döş ağrısı", "Siqaret, hipertansiyon"],
    vitals: [
      { label: "Temp", value: "36.8°C" },
      { label: "Nəbz", value: "98" },
      { label: "AT", value: "150/95" },
      { label: "SpO2", value: "94%" },
    ],
    patientContext: `Sən 58 yaşlı Vüsal adlı mühasibsən. 2 saatdan bəri döşündə çox pis, sıxıcı bir ağrın var — elə bil daş qoyublar. Sol qoluna, çənənə vurur. Çox tərləyirsən, ürəyin bulanır. İş yerinə sürətlə addımlayandan sonra başlayıb, dayanıb istirahət etsən də keçmir. 5 ildir qan təzyiqin yüksəkdir, amlodipine içirdin amma son bir həftədir içməmisən. 20 ildir siqaret çəkirsən. Çox qorxmusan, ölüm qorxusu hiss edirsən. Cavablarını birinci şəxsdə, xəstə kimi ver — məsələn "Mənim..." deyə başla. Qısa və təbii danış, tibbi termin işlətmə.`,
    historyQuestions: [
      { q: "Ağrı harada hiss olunur, başqa yerə yayılırmı?", a: "Döşümün ortasında — elə bil daş qoyublar. Sol qoluma, çənəmə də vurur." },
      { q: "Ağrı nə vaxtdan başlayıb, istirahətlə keçirmi?", a: "2 saat əvvəl sürətlə addımlayanda başladı. Oturdum, istirahət etdim — keçmədi, daha da gücləndi." },
      { q: "Siqaret çəkisinizmi, nə qədər müddətdir?", a: "Bəli, 20 ildən artıqdır, gündə bir paket çəkirəm." },
      { q: "Qan təzyiqiniz üçün dərman içirdinizmi?", a: "Həkimim amlodipine yazmışdı, amma son bir həftədir içməmişdim, unudurdum." },
      { q: "Daha öncə həkimə getmisinizmi?", a: "Bəli, ildə bir dəfə kardioloqa gedirəm, dərman yazmışdı, düzgün içmirdim." },
      { q: "Hansı dərmanları içirsiz?", a: "Amlodipine 5 mq yazılmışdı, amma son vaxt kəsmişdim." },
      { q: "Allergiyalarınız varmı?", a: "Xeyr, heç bir dərmana allergiyam olmayıb." },
      { q: "Ailənizdə oxşar xəstəlik olubmu?", a: "Atam 60 yaşında ürəkdən keçindi." },
    ],
    examinations: [
      { system: "Ürək", finding: "S4 gallop eşidilir, üfürüm yoxdur — hipertansiv fon, kəskin MI" },
      { system: "Ağciyərlər", finding: "Sol bazada incə krepitasiya — başlangıc ağciyər ödemi" },
      { system: "Dəri", finding: "Soyuq, tər basmış, solğun — periferik vazokonstriksiyanın əlaməti" },
      { system: "Boyun venaları", finding: "Hafif dolğunluq — ürək çatışmazlığının erkən əlaməti" },
    ],
    investigations: [
      { test: "EKQ", result: "V1–V4-də ≥2 mm ST elevasyonu — anterior STEMI mənzərəsi", relevant: true },
      { test: "Troponin I", result: "6.2 ng/mL (norm <0.04) — kəskin miokard zədəsinin biomarkeri", relevant: true },
      { test: "CK-MB", result: "188 U/L (yüksək) — miokard nekrozunu dəstəkləyir", relevant: true },
      { test: "Lipid profili", result: "LDL 4.6 mmol/L (yüksək) — əsas dəyişdirilə bilən risk faktoru", relevant: true },
      { test: "Tam qan analizi", result: "Normada", relevant: false },
      { test: "Sidik analizi", result: "Normada", relevant: false },
    ],
    correctDiagnosis: "Kəskin miokard infarktı (STEMI)",
    diagnosisKeywords: ["stemi", "miokard infarktı", "mi", "myocardial infarction", "ürək infarktı"],
    explanationPoints: [
      "EKQ-da V1–V4 ST elevasyonu — anterior STEMI, LAD oklüzyonu ehtimalı",
      "Troponin I 6.2 ng/mL — miokard nekrozunun əsas laborator təsdiqi",
      "S4 gallop + bazal krepitasiya — kəskin ürək çatışmazlığının başlanğıcı",
      "Amlodipini kəsmiş, hipertansiyon idarəsiz + 20 illik siqaret — kümülyativ risk",
      "Atanın 60 yaşında ürəkdən ölümü — güclü irsi risk faktoru",
    ],
    treatmentPoints: [
      "Aspirin 300 mq çeynənərək + Klopidogrel 600 mq yükləmə dozu (ikili antiagregant)",
      "Birincil PCI — door-to-balloon ≤90 dəqiqə (prioritet müdaxilə)",
      "PCI mövcud deyilsə: Tenekteplaz IV (doz çəkiyə görə: 30–50 mq)",
      "Nitrogliserin sublinqual (AT ≥90/60 mmHg olduqda — hipotansiyada əks-göstərişdir)",
      "Morfin 2–4 mq IV ağrı üçün (istifadəsi getdikcə mübahisəli — yalnız dözülməz ağrıda)",
      "Stabilizasiyadan sonra: Beta-blokator, ACE inhibitoru, Atorvastatin 80 mq/gün",
    ],
  },
  {
    id: 7,
    title: "Susuzluq və halsızlıq",
    specialty: "Endokrinologiya",
    difficulty: "Orta",
    patientSummary: "19 yaşlı qadın son 3 həftədə güclənən susuzluq, tez-tez sidiyə getmə, 5 kq çəki itkisi və ümumi halsızlıq şikayəti ilə müraciət edir. Son 2 gündür ürəkbulanması, qusma və qarın ağrısı əlavə olmuşdur. Tibbi tarixçəsindən əvvəllər diabet qeyd edilməyib.",
    tags: ["19 yaş · Qadın", "Susuzluq, çəki itkisi", "Tələbə, diabet tarixçəsi yoxdur"],
    vitals: [
      { label: "Temp", value: "37.1°C" },
      { label: "Nəbz", value: "118" },
      { label: "AT", value: "95/60" },
      { label: "SpO2", value: "98%" },
    ],
    patientContext: `Sən 19 yaşlı Aynur adlı tələbəsən. 3 həftədir çox su içirsən, amma susuzluğun getmir. Gecə dəfələrlə sidiyə durmalı olursan. 5 kilo arıqlamısan, pəhriz tutmamısan. 2 gündür ürəyin bulanır, qusurun var, qarnın ağrıyır. Annan ağzından xoşagəlməz bir qoxu gəldiyini deyib — meyvə kimidir, özün hiss etmirsən. Çox halsızsan, dərs oxuya bilmirsən. Nə olduğunu bilmirsən, qorxursan. Bir həftə əvvəl həkimə getmişdin, vitamin yazmışdı, kömək etməmişdi. Cavablarını birinci şəxsdə, xəstə kimi ver — məsələn "Mənim..." deyə başla. Qısa və təbii danış, tibbi termin işlətmə.`,
    historyQuestions: [
      { q: "Nə qədər su içirsiniz, susuzluğunuz keçirmi?", a: "Gündə 4–5 litr su içirəm, amma susuzluğum bir türlü keçmir." },
      { q: "Gecə neçə dəfə sidiyə durursunuz?", a: "Gecə 3–4 dəfə ayılıb gedirəm — bu əvvəl olmurdu." },
      { q: "Çəkiniz azalıbmı son vaxtlar?", a: "Bəli, 3 həftədə 5 kilo arıqladım, pəhriz tutmamışam, özüm də başa düşmürəm." },
      { q: "Ağzınızdan xüsusi bir qoxu gəlir deyirlərmi?", a: "Annam dedi ki, ağzımdan meyvəyə bənzər bir qoxu var, özüm hiss etmirəm." },
      { q: "Daha öncə həkimə getmisinizmi?", a: "Bəli, bir həftə əvvəl getmişdim, virus kimi bir şey deyib vitamin yazdı, kömək etmədi." },
      { q: "Hansı dərmanları içirsiz?", a: "Heç dərman içmirəm, o dəfə yazdığı vitamini bir-iki dəfə içdim, qaldı." },
      { q: "Allergiyalarınız varmı?", a: "Xeyr, bilmirəm heç allergiyam olub." },
      { q: "Ailənizdə şəkərli xəstəlik olubmu?", a: "Bibim şəkər xəstəliyindən dərman içir, amma onun xəstəliyi 50 yaşından sonra başlayıb." },
    ],
    examinations: [
      { system: "Ümumi görünüş", finding: "Letargik, dərin-sürətli (Kussmaul) tənəffüsü — metabolik asidozun respirator kompensasiyası" },
      { system: "Dəri və selikli qişalar", finding: "Dəri turqoru azalmış, dil quru — ağır dehidrasiya" },
      { system: "Nəfəs", finding: "Meyvəyəbənzər (aseton) qoxu — ketonemiyanın klinik əlaməti" },
      { system: "Qarın", finding: "Yayılmış ağrılılıq, müdafiə əlaməti yoxdur — DKA-da psevdoperitonit" },
    ],
    investigations: [
      { test: "Qan şəkəri", result: "28.4 mmol/L (512 mg/dL) — kəskin hiperglikemiya", relevant: true },
      { test: "Arterial qan qazı (AQQ)", result: "pH 7.17, HCO₃ 9 mEq/L — ağır metabolik asidoz", relevant: true },
      { test: "Sidik analizi", result: "Keton 3+, qlükoza 4+ — ketonuriya və qlükozuriya", relevant: true },
      { test: "HbA1c", result: "12.8% — uzun müddətli hiperqlisemiya, əvvəlcədən diaqnoz qoyulmayıb", relevant: true },
      { test: "Qaraciyər fermentləri", result: "Normada", relevant: false },
      { test: "Qan mədəniyyəti", result: "Mənfi", relevant: false },
    ],
    correctDiagnosis: "Diabetik ketoasidoz (DKA)",
    diagnosisKeywords: ["dka", "diabetik ketoasidoz", "diabetic ketoacidosis", "ketoasidoz", "tip 1 diabet"],
    explanationPoints: [
      "Qan şəkəri 28 mmol/L + keton 3+ + pH 7.17 — DKA-nın klassik diaqnostik üçlüyü",
      "Kussmaul tənəffüsü — metabolik asidoza respirator kompensasiya",
      "HbA1c 12.8% — diabet əvvəlcədən var imiş, diaqnoz qoyulmamışdı",
      "19 yaşlı, arıq, cəld başlangıc — Tip 1 DM ehtimalı yüksəkdir",
      "Meyvə qoxusu + sürətli arıqlama — proqressiv insulin çatışmazlığı",
    ],
    treatmentPoints: [
      "IV mayeləşdirmə: 0.9% NaCl 1 L/saat (birinci 1–2 saat), sonra 250–500 mL/saat",
      "Kalium ≥3.5 mEq/L olduqda Regular insulin infuziyası: 0.1 vahid/kq/saat IV",
      "Kalium <3.5 mEq/L olarsa: insulin vermədən əvvəl 20–40 mEq/saat KCl əlavə et",
      "Saatda bir monitorinq: qan şəkəri, elektrolitlər, AQQ",
      "Qan şəkəri 11 mmol/L-ə çatdıqda: 5% dekstroz + 0.45% NaCl-ə keç, insulini davam et",
      "Endokrinoloji konsultasiya, Tip 1 DM üçün bazal-bolus insulin sxemi planla",
    ],
  },
  {
    id: 8,
    title: "Öskürək, qızdırma, nəfəs darlığı",
    specialty: "Pulmonologiya",
    difficulty: "Asan",
    patientSummary: "35 yaşlı qadın müəllim 5 gündür davam edən yüksək qızdırma (39°C), sarı-yaşıl bəlğəmli öskürək və sağ tərəfdə nəfəs alanda güclənən döş ağrısı ilə müraciət edir. SpO₂ 92%-ə enib. Penisilin allergiyası var.",
    tags: ["35 yaş · Qadın", "Məhsuldar öskürək", "Məktəb mühiti, penisilin allergiyası"],
    vitals: [
      { label: "Temp", value: "39.1°C" },
      { label: "Nəbz", value: "104" },
      { label: "AT", value: "118/72" },
      { label: "SpO2", value: "92%" },
    ],
    patientContext: `Sən 35 yaşlı Gülnar adlı müəllimsən. 5 gündür yüksək hərarətin var, sarı-yaşıl bəlğəm çıxarırsan, nəfəs alanda sağ tərəfin bıçaq kimi sanır. Pilləkən qalxanda, bəzən otaqda gəzəndə belə nəfəsin çatmır. Məktəbdə işləyirsən, sinfindəki bir neçə uşaq da oxşar xəstə olmuşdu. 3 gün əvvəl həkimə getmişdin, parasetamol yazmışdı, kömək etmədi. Bir dəfə penisilin almışdın, o zaman dərimdə döküntü çıxmışdı — indi həkimə deyirsən ki, penisilinə allergiyam var. Cavablarını birinci şəxsdə, xəstə kimi ver — məsələn "Mənim..." deyə başla. Qısa və təbii danış, tibbi termin işlətmə.`,
    historyQuestions: [
      { q: "Öskürəyiniz məhsuldarlıdır, bəlğəm çıxırmı?", a: "Bəli, sarı-yaşıl bəlğəm çıxır, bəzən içində azacıq qan da görürəm." },
      { q: "Döş ağrısı nə vaxt güclənir?", a: "Nəfəs alanda və öskürəndə sağ tərəfdə bıçaq kimi sanır." },
      { q: "Ətrafınızda sizinki kimi xəstə olan var idimi?", a: "Bəli, sinfimin bir neçə uşağı oxşar şikayətlə xəstə olmuşdu." },
      { q: "Nəfəsiniz çatışmırmı?", a: "Bəli, pilləkən qalxanda, bəzən otaqda gəzəndə belə nəfəsim kəsilir." },
      { q: "Daha öncə həkimə getmisinizmi?", a: "Bəli, 3 gün əvvəl getdim, soyuqdəymə dedi, parasetamol yazdı, kömək etmədi." },
      { q: "Hansı dərmanları içirsiz?", a: "Parasetamol içirdim, azacıq kömək etdi amma xəstəlik davam edir." },
      { q: "Allergiyalarınız varmı?", a: "Bəli, penisilinə allergiyam var — əvvəl aldığımda dərimdə döküntü çıxmışdı." },
      { q: "Ailənizdə ağciyər xəstəliyi olubmu?", a: "Xeyr, ailəmdə belə xəstəlik olmayıb." },
    ],
    examinations: [
      { system: "Ağciyərlər (auskultasiya)", finding: "Sağ alt lobda bronxial tənəffüs və krepitasiya — alveolar konsolidasiya" },
      { system: "Ağciyərlər (perkussiya)", finding: "Sağ alt lobda mattlıq — konsolidasiya sahəsi" },
      { system: "Ümumi görünüş", finding: "Toksik görünüş, yanaqlar qırmızı, qızdırmalı" },
    ],
    investigations: [
      { test: "Döş qəfəsi rentgeni", result: "Sağ alt lobda homojen infiltrat — lobar pnevmoni mənzərəsi", relevant: true },
      { test: "Tam qan analizi", result: "Lökositoz 17×10⁹/L, nötrofil üstünlüyü — bakterial infeksiya", relevant: true },
      { test: "CRP", result: "162 mg/L (yüksək) — aktiv iltihab prosesi", relevant: true },
      { test: "Bəlğəm mədəniyyəti", result: "Streptococcus pneumoniae üremişdir — penisilinə həssas", relevant: true },
      { test: "Sidik analizi", result: "Normada", relevant: false },
      { test: "Qaraciyər fermentləri", result: "Normada", relevant: false },
    ],
    correctDiagnosis: "İcma mənşəli pnevmoniya (CAP)",
    diagnosisKeywords: ["pnevmoniya", "pneumonia", "cap", "icma mənşəli pnevmoniya", "ağciyər iltihabı"],
    explanationPoints: [
      "Rentgendə sağ alt lob infiltratı — lobar pnevmoniyanın görüntüsü",
      "Bəlğəm mədəniyyətindən S. pneumoniae — ən çox rast gəlinən CAP törədicisi",
      "SpO₂ 92% — oksigen terapiyasının göstəricisi",
      "Məktəb epidemik mühiti — infeksiya mənbəyinin izlənməsi",
      "Penisilin allergiyası — beta-laktam əks-göstərişdir, müalicə uyğunlaşdırılmalıdır",
    ],
    treatmentPoints: [
      "Penisilin allergiyası var — amoksisilin/amoksiklav əks-göstərişdir",
      "Azitromisine 500 mq 1-ci gün, sonra 250 mq/gün × 4 gün (makrolid seçimi)",
      "Alternativ (ağır kurs): Moksifloksasin 400 mq/gün və ya Levofloksasin 750 mq/gün",
      "Oksigen terapiyası: SpO₂ ≥95% hədəfləmək",
      "Bol maye, istirahət, ateş üçün parasetamol",
      "6 həftə sonra nəzarət rentgen (infiltratın tam keçdiyini təsdiqlə)",
    ],
  },
  {
    id: 9,
    title: "Bel ağrısı və qızdırma",
    specialty: "Nefrologiya",
    difficulty: "Asan",
    patientSummary: "28 yaşlı qadın 2 gündür davam edən sağ bel ağrısı, yüksək qızdırma (39°C), tez-tez sidiyə getmə və sidikdə yanğı şikayəti ilə müraciət edir. Bir həftə əvvəl sidik yolu şikayətlərini müalicəsiz keçirməyə çalışdığını bildirir.",
    tags: ["28 yaş · Qadın", "Bel ağrısı, sidik yanğısı", "Residiv sidik yolu infeksiyası"],
    vitals: [
      { label: "Temp", value: "39.2°C" },
      { label: "Nəbz", value: "108" },
      { label: "AT", value: "105/68" },
      { label: "SpO2", value: "98%" },
    ],
    patientContext: `Sən 28 yaşlı Sevinc adlı ofis işçisisən. 2 gündür sağ böyrəyin olduğu yerdə, arxadan güclü ağrın var, həm də qızdırman var. Sidiyə gedəndə yanır, tez-tez getməli olursan amma çox az gəlir. Bir həftə əvvəl də sidik şikayətin var idi, öz-özünə keçər bildim getmədim — keçmədi, indi daha pis oldu. Bu mövzuda danışmaq bir az utandırır sənə. Cavablarını birinci şəxsdə, xəstə kimi ver — məsələn "Mənim..." deyə başla. Qısa və təbii danış, tibbi termin işlətmə.`,
    historyQuestions: [
      { q: "Bel ağrısı bir tərəfdədir, yoxsa iki tərəfdə?", a: "Sağ tərəfdə, arxadan, böyrəyimin olduğu yerdə." },
      { q: "Sidiyə gedəndə yanğı olur mu, tez-tez gedirsizmi?", a: "Bəli, həm yanır, həm 30 dəqiqədən bir getməliyəm, amma çox az gəlir." },
      { q: "Bir həftə əvvəl də sidik şikayətiniz var idi — o zaman nə etdiniz?", a: "Var idi, həkimə getmədim, öz-özünə keçər bildim. Keçmədi, indi daha pis oldu." },
      { q: "Son vaxtlar cinsi əlaqənizdə dəyişiklik olubmu?", a: "Ərim məzuniyyətdən yenə qayıtdı... bəlkə onunla əlaqəlidir, bilmirəm." },
      { q: "Daha öncə həkimə getmisinizmi?", a: "Bəli, dəfələrlə sidik yolu iltihabım olub, antibiotik içmişəm." },
      { q: "Hansı dərmanları içirsiz?", a: "Hazırda heç bir dərman içmirəm." },
      { q: "Allergiyalarınız varmı?", a: "Xeyr, heç bir allergiyam yoxdur." },
      { q: "Ailənizdə böyrək xəstəliyi olubmu?", a: "Anamın böyrəyi zəifdir, daşı da olmuşdu əvvəllər." },
    ],
    examinations: [
      { system: "Böyrək nahiyəsi", finding: "Sağ kostovertebral bucaqda döyüntü ağrısı müsbət — piyelonefritin əsas klinik əlaməti" },
      { system: "Qarın", finding: "Sağ böyrək proyeksiyasında ağrılılıq, peritoneal əlamətlər yoxdur" },
      { system: "Ümumi görünüş", finding: "Qızdırmalı, narahat — sistemli infeksiya əlaməti" },
    ],
    investigations: [
      { test: "Sidik analizi", result: "Piyuriya (>10 lökosit/sahə), nitrit müsbət, bakteriuriya — sidik yolu infeksiyası", relevant: true },
      { test: "Sidik mədəniyyəti", result: "E. coli >10⁵ KOE/mL, siprofloksasinə həssas", relevant: true },
      { test: "Tam qan analizi", result: "Lökositoz 15×10⁹/L — bakterial infeksiyaya sistemli cavab", relevant: true },
      { test: "Böyrək USM", result: "Sağ böyrək 1 sm böyümüş, pelvikalikal sistem yüngül genişlənib — obstruksiya istisna edildi", relevant: true },
      { test: "Qan şəkəri", result: "Normada", relevant: false },
      { test: "Döş qəfəsi rentgeni", result: "Normada", relevant: false },
    ],
    correctDiagnosis: "Kəskin piyelonefrit",
    diagnosisKeywords: ["piyelonefrit", "pyelonephritis", "böyrək iltihabı", "kəskin piyelonefrit", "sidik yolu infeksiyası"],
    explanationPoints: [
      "Kostovertebral bucaqda döyüntü ağrısı — böyrək kapsulunun gərginliyinin əlaməti",
      "Sidikdə piyuriya + nitrit + E. coli mədəniyyəti — bakterial etioloji təsdiqləndi",
      "Müalicəsiz sistitin bir həftə sonra yuxarı yollara yayılması",
      "Lökositoz 15×10⁹/L — sistemik infeksiya cavabı",
      "USM-də obstruksiya istisna edildi — sadə piyelonefrit, cərrahi lazım deyil",
    ],
    treatmentPoints: [
      "Siprofloksasin 500 mq × 2 dəfə/gün, 14 gün (E. coli həssaslığı varsa)",
      "Alternativ (ağır, qusma varsa): Seftriakson 1–2 q IV/IM, hospitallaşdırma",
      "Bol maye içmə (gündə ≥2 litr)",
      "Analqezik: İbuprofen 400 mq × 3 dəfə/gün yemək üstündə",
      "Müalicə bitdikdən 5–7 gün sonra sidik mədəniyyəti nəzarəti (eradikasiya yoxlanılsın)",
      "Residiv piyelonefrit varsa üroloji qiymətləndirmə (sistoskopiya, anatomik qüsur axtarılsın)",
    ],
  },
  {
    id: 10,
    title: "Mədə ağrısı və qara nəcis",
    specialty: "Qastroenterologiya",
    difficulty: "Orta",
    patientSummary: "45 yaşlı kişi 3 aydır davam edən epiqastrik ağrı (xüsusilə ac qarnına güclənən) və son 2 gündür qara, qatranvari nəcis şikayəti ilə müraciət edir. Diz artrozu üçün uzun müddət ibuprofen qəbul edir. Qan analizi anemiya göstərir.",
    tags: ["45 yaş · Kişi", "Epiqastrik ağrı, melena", "Uzunmüddətli NSAID istifadəsi"],
    vitals: [
      { label: "Temp", value: "36.9°C" },
      { label: "Nəbz", value: "96" },
      { label: "AT", value: "115/74" },
      { label: "SpO2", value: "97%" },
    ],
    patientContext: `Sən 45 yaşlı Tofiq adlı tikilişçisən. 3 aydır mədənin yuxarı hissəsi ağrıyır — xüsusilə ac qalsan çox pis olur, bir şey yesən azacıq yaxşılaşır. 2 gündür nəcisin qara, qatran kimi — bu sənə çox qorxudu. Diz ağrın üçün gündə 2–3 dəfə ibuprofen içirsən, həkiminin yazdığı dərmandır. Siqaret çəkirsən. Bir ay əvvəl həkimə getmişdin, mədə dərmanı yazmışdı, azacıq kömək etmişdi amma ibuprofeni kəsməmişdin. Cavablarını birinci şəxsdə, xəstə kimi ver — məsələn "Mənim..." deyə başla. Qısa və təbii danış, tibbi termin işlətmə.`,
    historyQuestions: [
      { q: "Ağrı yeməkdən sonra azalırmı, yoxsa güclənirmi?", a: "Yesəm azalır, ac qalsam çox pis olur — xüsusilə gecə çox ağrıyır." },
      { q: "Hansı ağrı kəsici dərmanları istifadə edirsiniz?", a: "Diz ağrım üçün ibuprofen içirəm, həkim yazmışdı, gündə 2–3 dəfə." },
      { q: "Nəcisinizin rəngi nə vaxtdan dəyişib?", a: "2 gündür qara, qatran kimi — əvvəl belə olmurdu, çox qorxdum." },
      { q: "Siqaret içirsinizmi?", a: "Bəli, gündə yarım paket çəkirəm, artıq 20 ildən çoxdur." },
      { q: "Daha öncə həkimə getmisinizmi?", a: "Bəli, bir ay əvvəl getdim, mədə üçün dərman yazdı, azacıq kömək etdi." },
      { q: "Hansı dərmanları içirsiz?", a: "İbuprofen gündə 2–3 dəfə, bəzən mədə yandıqda antasid içirəm." },
      { q: "Allergiyalarınız varmı?", a: "Xeyr, heç bir allergiyam yoxdur." },
      { q: "Ailənizdə mədə xəstəliyi olubmu?", a: "Atamın mədəsi var idi, qan da getmişdi, əməliyyat etmişdilər." },
    ],
    examinations: [
      { system: "Qarın", finding: "Epiqastrik nahiyədə orta dərəcəli ağrılılıq, peritoneal əlamətlər yoxdur — perforasiya istisna edildi" },
      { system: "Rektal müayinə", finding: "Melena (qara, qatranvari nəcis) — üst GİT qanamaya dəlalət edir" },
      { system: "Ümumi görünüş", finding: "Solğun görünüş, hafif taxikardiya — xronik qan itkisi" },
    ],
    investigations: [
      { test: "H. pylori (nəfəs testi)", result: "Müsbət — peptik xoranın əsas etioloji amili", relevant: true },
      { test: "Tam qan analizi", result: "Hb 9.6 q/dL, MCV azalmış — xronik dəmir çatışmazlığı anemiyası", relevant: true },
      { test: "EFQDS (endoskopiya)", result: "Duodenum bulbusunda 1.2 sm xora, görünən damar (Forrest IIa) — yüksək residiv qanama riski", relevant: true },
      { test: "Abdominal USM", result: "Qaraciyər, öd kisəsi normada — daş yoxdur", relevant: false },
      { test: "Sidik analizi", result: "Normada", relevant: false },
    ],
    correctDiagnosis: "Duodenal xora (peptik xora xəstəliyi)",
    diagnosisKeywords: ["peptik xora", "duodenal xora", "peptic ulcer", "mədə xorası", "duodenum xorası"],
    explanationPoints: [
      "Ac qarnına ağrı, yeməklə yaxşılaşma — duodenal xoranın klassik klinik mənzərəsi",
      "Melena — üst GİT qanamadan; ≥50 mL qan itkisini bildirir",
      "H. pylori müsbət + uzun müddətli NSAID (ibuprofen) — iki əsas risk faktoru birlikdə",
      "Endoskopiyada görünən damar (Forrest IIa) — müdaxiləsiz ~50% residiv qanama riski",
      "Hb 9.6 q/dL, MCV azalmış — xronik dəmir çatışmazlığı anemiyası, kəskin qanama deyil",
    ],
    treatmentPoints: [
      "İbuprofeni dərhal dayandır — NSAID peptik xoranın birbaşa səbəbidir",
      "H. pylori eradikasiyası: Omeprazol 20 mq × 2 + Klaritromisine 500 mq × 2 + Amoksisilin 1 q × 2 — 14 gün",
      "Endoskopik hemostaz: Termokoaqulyasiya + klips (Forrest IIa xora üçün)",
      "PPI yüksək dozada: Omeprazol 40 mq × 2/gün IV (qanama endoskopiyadan sonra 72 saat)",
      "Dəmir preparatı: Dəmir sulfat 325 mq × 3 dəfə/gün anemiya üçün",
      "4–8 həftə sonra nəfəs testi ilə H. pylori eradikasiyasını yoxla",
    ],
  },
]
